<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\LsuController;
use App\Http\Controllers\BlokController;
use App\Http\Controllers\UnitController;
use App\Http\Controllers\JalanController;
use App\Http\Controllers\LegalController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ArestaController;
use App\Http\Controllers\ChInputController;
use App\Http\Controllers\NurseryController;
use App\Http\Controllers\PayrollController;
use App\Http\Controllers\ProduksiController;
use App\Http\Controllers\AirSungaiController;
use App\Http\Controllers\AnalisaProdController;
use App\Http\Controllers\AramcoController;
use App\Http\Controllers\PerawatanController;
use App\Http\Controllers\ContractpkController;
use App\Http\Controllers\CurahHujanController;
use App\Http\Controllers\PupukRawatController;
use App\Http\Controllers\ArestaInputController;
use App\Http\Controllers\AwsController;
use App\Http\Controllers\AwsInputController;
use App\Http\Controllers\BlokKordinatController;
use App\Http\Controllers\ContractcpoController;
use App\Http\Controllers\FfbInternalController;
use App\Http\Controllers\ProduksicpoController;
use App\Http\Controllers\TbsInternalController;
use App\Http\Controllers\FfbEksternalController;
use App\Http\Controllers\LhoController;
use App\Http\Controllers\PupukrawatinputController;
use App\Http\Controllers\PanenController;
use App\Http\Controllers\LhodepreController;
use App\Http\Controllers\LhoinputController;
use App\Http\Controllers\LhospartController;
use App\Http\Controllers\PemupukanKebunController;
use App\Http\Controllers\PerawatanKebunController;
use App\Http\Controllers\PremiController;
use App\Http\Controllers\RealisasiPanenController;
use App\Http\Controllers\RentalController;
use App\Http\Controllers\RestanController;
use App\Http\Controllers\SptbsInputController;
use App\Http\Controllers\TSAController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/user', UserController::class);
Route::get('/user/hapus/{id}', [UserController::class, 'destroy']);
Route::post('/user/changePassword/{id}', [UserController::class, 'changePassword'])->name('user.changePassword');
Route::resource('/comp', CompanyController::class);
Route::get('/comp/hapus/{id}', [CompanyController::class, 'destroy']);
Route::resource('/aresta', ArestaController::class);
Route::get('/airsungai/data', [AirSungaiController::class, 'data'])->name('airsungai.data');
Route::get('/airsungai/export/excel',[AirSungaiController::class, 'exportExcel'])->name('airsungai.export.excel');
Route::get('/airsungai/export/pdf', [AirSungaiController::class, 'exportPdf'])->name('airsungai.export.pdf');
Route::resource('/airsungai', AirSungaiController::class);
Route::post('/airsungai/store', [AirSungaiController::class, 'store'])->name('airsungai.store');
Route::get('/airsungai/hapus/{id}', [AirSungaiController::class, 'destroy']);
Route::post('/airsungai', [AirSungaiController::class, 'import'])->name('airsungai.import');
Route::get('/curah/data', [ChInputController::class, 'data'])->name('curah.data');
Route::get('/curah/export/excel',[ChInputController::class, 'exportExcel'])->name('curah.export.excel');
Route::get('/curah/export/pdf',[ChInputController::class, 'exportPdf'])->name('curah.export.pdf');
Route::resource('/curah', ChInputController::class);
Route::post('/curah/store', [ChInputController::class, 'store'])->name('curah.store');
Route::post('/curah', [ChInputController::class, 'import'])->name('curah.import');
Route::get('/curah/hapus/{id}', [ChInputController::class, 'destroy']);
Route::get('/areal/data', [ArestaInputController::class, 'data'])->name('areal.data');
Route::post('/areal/import', [ArestaInputController::class, 'import'])->name('areal.import');
Route::get('/areal/export/excel', [ArestaInputController::class, 'exportExcel'])->name('areal.export.excel');
Route::get('/areal/export/pdf', [ArestaInputController::class, 'exportPdf'])->name('areal.export.pdf');
Route::resource('/areal', ArestaInputController::class);
Route::get('/tbsinternal/data', [TbsInternalController::class, 'data'])->name('tbsinternal.data');
Route::resource('/tbsinternal', TbsInternalController::class);
Route::post('/tbsinternal/save', [TbsInternalController::class, 'save'])->name('tbsinternal.save');
Route::get('/tbsinternal/hapus/{id}', [TbsInternalController::class, 'destroy']);
Route::post('/tbsinternal', [TbsInternalController::class, 'import'])->name('tbsinternal.import');
Route::resource('/panen', PanenController::class);
Route::get('/panen/hapus/{id}', [PanenController::class, 'destroy']);
Route::get('/ffbinternal/data', [FfbInternalController::class, 'data'])->name('ffbinternal.data');
Route::get('/ffbinternal/export/excel',[FfbInternalController::class, 'exportExcel'])->name('ffbinternal.export.excel');
Route::get('/ffbinternal/export/pdf', [FfbInternalController::class, 'exportPdf'])->name('ffbinternal.export.pdf');
Route::post('/ffbinternal/simpan', [FfbInternalController::class, 'simpan'])->name('ffbinternal.simpan');
Route::resource('/ffbinternal', FfbInternalController::class);
Route::post('/ffbinternal', [FfbInternalController::class, 'import'])->name('ffbinternal.import');
Route::get('/ffbekternal/data', [FfbEksternalController::class, 'data'])->name('ffbeksternal.data');
Route::get('/ffbeksternal/export/excel', [FfbEksternalController::class, 'exportExcel'])->name('ffbeksternal.export.excel');
Route::get('/ffbeksternal/export/pdf', [FfbEksternalController::class, 'exportPdf'])->name('ffbeksternal.export.pdf');
Route::resource('/ffbeksternal', FfbEksternalController::class);
Route::post('/ffbeksternal', [FfbEksternalController::class, 'import'])->name('ffbeksternal.import');
Route::get('/produksicpo/data', [ProduksicpoController::class, 'data'])->name('produksicpo.data');
Route::get('/produksicpo/export/excel', [ProduksicpoController::class, 'exportExcel'])->name('produksicpo.export.excel');
Route::get('/produksicpo/export/pdf', [ProduksicpoController::class, 'exportPdf'])->name('produksicpo.export.pdf');
Route::resource('/produksicpo', ProduksicpoController::class);
Route::post('/produksicpo', [ProduksicpoController::class, 'import'])->name('produksicpo.import');
Route::get('/contractcpo/data', [ContractcpoController::class, 'data'])->name('contractcpo.data');
Route::resource('/contractcpo', ContractcpoController::class);
Route::post('/contractcpo', [ContractcpoController::class, 'import'])->name('contractcpo.import');
Route::resource('/contractpk', ContractpkController::class);
Route::post('/contractpk', [ContractpkController::class, 'import'])->name('contractpk.import');
Route::resource('/pupuk', PupukrawatinputController::class);
Route::post('/pupuk', [PupukrawatinputController::class, 'import'])->name('pupuk.import');
Route::resource('/perawatan', PerawatanController::class);
Route::post('/perawatan', [PerawatanController::class, 'import'])->name('perawatan.import');
Route::resource('/payroll', PayrollController::class);
Route::post('/payroll', [PayrollController::class, 'import'])->name('payroll.import');
Route::resource('/lho', LhoController::class);
Route::post('/lho', [LhoController::class, 'import'])->name('lhobbm.import');
Route::resource('/depre', LhodepreController::class);
Route::post('/depre', [LhodepreController::class, 'import'])->name('lhodepre.import');
Route::resource('/spartlho', LhospartController::class);
Route::post('/spartlho', [LhospartController::class, 'import'])->name('spartlho.import');
Route::resource('/lhounit', LhoinputController::class);
Route::post('/lhounit', [LhoinputController::class, 'import'])->name('lhounit.import');
Route::resource('/curahhujan', CurahHujanController::class);
Route::resource('/produksi', ProduksiController::class);
Route::resource('/pr', PupukRawatController::class);
Route::resource('/vra', UnitController::class);
Route::resource('/road', JalanController::class);
Route::resource('/legal', LegalController::class);
Route::resource('/lsu', LsuController::class);
Route::resource('/blok', BlokController::class);
Route::resource('/bibit', NurseryController::class);
Route::resource('/aws', AwsController::class);
Route::resource('/produksikebun', AnalisaProdController::class);
Route::get('/realisasipanen/data', [RealisasiPanenController::class, 'data'])->name('realisasipanen.data');
Route::post('/realisasipanen/import', [RealisasiPanenController::class, 'import'])->name('realisasipanen.import');
Route::get('/realisasipanen/export/excel', [RealisasiPanenController::class, 'exportExcel'])->name('realisasipanen.export.excel');
Route::get('/realisasipanen/export/pdf', [RealisasiPanenController::class, 'exportPdf'])->name('realisasipanen.export.pdf');
Route::get('/realisasipanen/hapus/{id}', [RealisasiPanenController::class, 'destroy']);
Route::resource('/realisasipanen', RealisasiPanenController::class);
Route::get('/laprestan/data', [RestanController::class, 'data'])->name('laprestan.data');
Route::post('/laprestan/import', [RestanController::class, 'import'])->name('laprestan.import');
Route::get('/laprestan/export/excel', [RestanController::class, 'exportExcel'])->name('laprestan.export.excel');
Route::get('/laprestan/export/pdf', [RestanController::class, 'exportPdf'])->name('laprestan.export.pdf');
Route::get('/laprestan/hapus/{id}', [RestanController::class, 'destroy']);
Route::resource('/laprestan', RestanController::class);
Route::get('/sptbs/data', [SptbsInputController::class, 'data'])->name('sptbs.data');
Route::post('/sptbs/import', [SptbsInputController::class, 'import'])->name('sptbs.import');
Route::get('/sptbs/export/excel', [SptbsInputController::class, 'exportExcel'])->name('sptbs.export.excel');
Route::get('/sptbs/export/pdf', [SptbsInputController::class, 'exportPdf'])->name('sptbs.export.pdf');
Route::post('/sptbs/simpan', [SptbsInputController::class, 'simpan'])->name('sptbs.simpan');
Route::resource('/sptbs', SptbsInputController::class);
Route::get('/awsinput/data/', [AwsInputController::class, 'data'])->name('awsinput.data');
Route::post('/awsinput/import', [AwsInputController::class, 'import'])->name('awsinput.import');
Route::get('/awsinput/export/excel', [AwsInputController::class, 'exportExcel'])->name('awsinput.export.excel');
Route::get('/awsinput/export/pdf', [AwsInputController::class, 'exportPdf'])->name('awsinput.export.pdf');
Route::resource('/awsinput', AwsInputController::class);
Route::get('/premi/data', [PremiController::class, 'data'])->name('premi.data');
Route::post('/premi/import', [PremiController::class, 'import'])->name('premi.import');
Route::get('/premi/export/excel', [PremiController::class, 'exportExcel'])->name('premi.export.excel');
Route::get('/premi/export/pdf', [PremiController::class, 'exportPdf'])->name('premi.export.pdf');
Route::resource('/premi', PremiController::class);
Route::get('/rental/data', [RentalController::class, 'data'])->name('rental.data');
Route::post('/rental/import', [RentalController::class, 'import'])->name('rental.import');
Route::get('/rental/export/excel', [RentalController::class, 'exportExcel'])->name('rental.export.excel');
Route::get('/rental/export/pdf', [RentalController::class, 'exportPdf'])->name('rental.export.pdf');
Route::resource('/rental', RentalController::class);
Route::get('/pupukkebun/data', [PemupukanKebunController::class, 'data'])->name('pupukkebun.data');
Route::post('/pupukkebun/import', [PemupukanKebunController::class, 'import'])->name('pupukkebun.import');
Route::get('/pupukkebun/export/excel', [PemupukanKebunController::class, 'exportExcel'])->name('pupukkebun.export.excel');
Route::get('/pupukkebun/export/pdf', [PemupukanKebunController::class, 'exportPdf'])->name('pupukkebun.export.pdf');
Route::resource('/pupukkebun', PemupukanKebunController::class);
Route::get('/rawatkebun/data', [PerawatanKebunController::class, 'data'])->name('rawatkebun.data');
Route::post('/rawatkebun/import', [PerawatanKebunController::class, 'import'])->name('rawatkebun.import');
Route::get('/rawatkebun/export/excel', [PerawatanKebunController::class, 'exportExcel'])->name('rawatkebun.export.excel');
Route::get('/rawatkebun/export/pdf', [PerawatanKebunController::class, 'exportPdf'])->name('rawatkebun.export.pdf');
Route::resource('/rawatkebun', PerawatanKebunController::class);
Route::get('/aramco/data', [AramcoController::class, 'data'])->name('aramco.data');
Route::post('/aramco/import', [AramcoController::class, 'import'])->name('aramco.import');
Route::get('/aramco/export/excel', [AramcoController::class, 'exportExcel'])->name('aramco.export.excel');
Route::get('/aramco/export/pdf', [AramcoController::class, 'exportPdf'])->name('aramco.export.pdf');
Route::resource('/aramco', AramcoController::class);
Route::get('/blokkoordinat/data', [BlokKordinatController::class, 'data'])->name('blokkoordinat.data');
Route::post('/blokkoordinat/import', [BlokKordinatController::class, 'import'])->name('blokkoordinat.import');
Route::get('/blokkoordinat/export/excel', [BlokKordinatController::class, 'exportExcel'])->name('blokkoordinat.export.excel');
Route::get('/blokkoordinat/export/pdf', [BlokKordinatController::class, 'exportPdf'])->name('blokkoordinat.export.pdf');
Route::resource('/blokkoordinat', BlokKordinatController::class);
Route::get('/tsa/data', [TSAController::class, 'data'])->name('tsa.data');
Route::resource('/tsa', TSAController::class);